### ISSUE TITLE
More precise font size

### ISSUE THREAD

**Issue by harm-less** [fraywing/textAngular#1055]
Hello,

Today I've implemented textAngular which was easy. However, adding extra tools wasn't the most easy task. I could add a colorpicker without too much trouble but a text size tool was missing to my surprise. 
In the repository issues I could find people who build their own but they seem to only use 6 sizes using `<font size="1/2/3...."></font`. However, I would like to change the text size based on pixels.

When I started looking in the source and the Rangy source to look at what it's possible, I couldn't find an easy solution. Is this a feature that will be implemented in the future?

Or is it possible to change the inline style properties of a selected piece of text so I can apply something like `font-size: 14px` for example?

Regards,
Harm

**Comment by pbassut** [comment]
I was going to offer you to implement this in a dropdown support using taTool. But due to https://github.com/fraywing/textAngular/issues/397 this is not possible yet. Unless you don't care about the UI. But the only way I see fonts being selected is in a dropdown sort of thing.

But adding and inline ```font-size``` is perfectly possible. Did you have any problems with it?
