### ISSUE TITLE
angular sanitize 1.4.8 doesn't work

### ISSUE THREAD

**Issue by andyczerwonka** [fraywing/textAngular#1076]
When I include angular sanitize from the 1.4.8 distro, I get an error.
```
Uncaught Error: [textAngular:textAngularSetup] http://errors.angularjs.org/1.4.8/textAngular/textAngularSetup?p0=The%20tex…0another%20--%20have%20you%20included%20angular-sanitize%20by%20mistake%3F
```

**Comment by donaldinou** [comment]
I think you need to do something like this in your angular.module().config method:

```
    $provide.decorator('taOptions', ['$delegate', function(taOptions) {
        taOptions.forceTextAngularSanitize = false;
        return taOptions;
    }]);
```

Do not forget to inject $provide

**Comment by varmint09** [comment]
@donaldinou +1

I would agree the inverse would make a more logical default...

**Comment by pbassut** [comment]
@donaldinou Imagine how many people would not know about a "sanitizer" and be a possible target to attacks like XSS. 
This is a security concern. That way you'll only disable if you know what you're doing.

But the cause of the problem is actually having both ta-sanitizer and angular-sanitizer included.

It has nothing to do with disabling the ta-sanitizer although it will work, also will make your app vulnerable to attacks as mentioned above.

**Comment by andyczerwonka** [comment]
I also agree, the default is better using angular sanitize.

**Comment by donaldinou** [comment]
@pbassut, my interrogation is notre about the use of a sanitize, but about to force the use of textangular sanitize which is an older version of angular sanitize... So if you concern about security. Otherwise, everything goes well

**Comment by andyczerwonka** [comment]
@donaldinou +1

**Comment by pbassut** [comment]
@donaldinou There's some things the angular sanitizer won't strip. I remember @SimeonC talking about it somewhere but I can't remember where. 
Also, I think is very obvious that using angular default's sanitizer a good idea. We [and others](https://github.com/froala/angular-froala/blob/master/src/froala-sanitize.js) wouldn't do so if we didn't find a barrier that prevented us to.
