### ISSUE TITLE
Browser spelling correction not setting the control to dirty

### ISSUE THREAD

**Issue by YoungYoungs** [fraywing/textAngular#1120]
Hi,

When using chrome, if a spelling mistake is corrected using a right click and then selecting the browser spelling suggestion from the context menu, the control and containing form are not set to dirty. This does happen when using standard text area.

So this makes it hard to detect changes to the text if these come from spelling corrections.

I have several controls on a page and in order to force the browser to show all spelling mistakes at once I spin through the controls setting the focus. Admittedly this is a bit of a hack but does the job.

I have made this plunker to show the difference in behaviour between textAngular and a standard text area. http://plnkr.co/edit/x63SYk?p=preview

Is this expected behaviour? Am I missing something?

Thanks in advance

**Comment by pbassut** [comment]
It looks like a relatively easy to fix bug. Although we've got a lot of critical ones on the line. So this might not be here on the next release.

Thanks for reporting this.

**Comment by YoungYoungs** [comment]
Great thanks

**Comment by JoelParke** [comment]
<p>This is now fixed with <span style="font-size: 14px;float: none;">PR </span><a href="https://github.com/fraywing/textAngular/pull/1321" class="issue-link js-issue-link" title="fix(taBind): Browser spelling correction not setting the control to d…" style="background-color: rgb(255, 255, 255);color: rgb(64, 120, 192);font-size: 14px;">#1321</a><span style="font-size: 14px;float: none;">. and will be in the next release.  It was not very easy, and I believe that this fix takes care of this issue.  It now properly updates the ngModel, etc.  </span></p><p><span style="font-size: 14px;float: none;">Could you retest and re-open if still an issue.</span></p>
