### ISSUE TITLE
Toolbar enables on every instance

### ISSUE THREAD

**Issue by ChrisB92** [fraywing/textAngular#1266]
I've been experiencing an issue with textAngular that I can't, for the life of me, figure out.

I have multiple instances of textAngular on a page that get initialised by a directive. Every instance has a unique name and id.

When I select one instance, the toolbar on every instance activates and replicates any formatting selection.

I was hoping that someone has had this issue before and managed to solve it.

Just to reiterate:
- Every instance has a unique name and id attribute
- Every instance is called by a directive
- There are no console errors

Here is a screenshot showing the issue:
![screenshot 2016-08-09 13 16 14](https://cloud.githubusercontent.com/assets/1481712/17515979/98a9d5fa-5e33-11e6-99ff-b023e530b612.png)

**Comment by eehaddad** [comment]
I also have this issue. Reverted back to 1.5.2 for now. 
I'll try to dig into this and see what is causing this. If anyone has any ideas please advise. 
Thanks.

**Comment by JoelParke** [comment]
I am in the middle to a deep rewrite/restructuring of some very subtle DOM code and will be occupied with this for at least a week for so.  Attempting to repair/enhance v1.5.4 so I can't take look at this issue.  BUT given that v1.5.2 works correctly and v1.5.3 is an issue.  

Please take a look at the changes here:
https://github.com/fraywing/textAngular/commit/d373fe10e770bf521641975cbc6a4f480d0a1f9e
and 
https://github.com/fraywing/textAngular/commit/0d860d0a97c440b868639bfb3ea9f3f943658da6

These changes automatically update the styles on the toolbars (an important change/fix) but perhaps this changes interacts with what you have built/structured.  One simple test, would be to disable these changes in the v1.5.3 release and then if that helps, to learn exactly why.

I hope this helps...

**Comment by JoelParke** [comment]
I just released v1.5.5 which fixes some things.   Please let me know if this is still an issue and I will tackle it next.  Thanks!

**Comment by llafuente** [comment]
Partially solved.

I can't press some buttons before, but now all are working.
But now the action is done in all textAngular(s) not just selected one.

I can't create a plunkr to reproduce... even copy my HTML didn't work :cry: 

The first symptom is that toolbars are not disabled.
When a textAngular is selected, the others toolbars are disabled, but under-unkown-circunstances that's not the case. 

The bug is exposed by d373fe1
Now you are applying styles to all editors @updateStyles, that's very suspicious... why?
And I think in another part you read that modification an apply the changes to all editors.

But I really think the real bug is "not-disabled" toolbars...

Hope it helps.

**Comment by JoelParke** [comment]
This is fixed with a commit... and PR.  Thanks, sorry for the bug!

**Comment by JoelParke** [comment]
Fixed in v1.5.7
