### ISSUE TITLE
textAngular output html error link on Firefox

### ISSUE THREAD

**Issue by thanhngch** [fraywing/textAngular#1277]
Steps:
Issue 1.
1. Go to http://textangular.com/ in Firefox or Edge
2. Focus in editor , ctrl + A, del to delete all content
3. Write hi, ctrl + A, click button link, input hi.com in text box.
4. The HTML output is `<p><a href="http://hi.com" target=""></a></p><p>hi<br/></p>` in Firefox,
and output `<p><a href="http://hi.com" target="">hi</a></p>` in Chrome.

Issue 2.
1. click toggle html
2. paste `<p><a href="http://hi.com" target="">hi</a><br></p>`
3. toggle html, write space and some text, it's difference in Firefox and chrome.

**Comment by JoelParke** [comment]
There is a part of me that hates Firefox :-).  I will see if I can work around this without breaking all the new fixes or other issues with Firefox.  Thanks very much for pointing this out so carefully and determining the exact use case.  

This issue is worse in that the <a></a>'s seems to grab the focus and additional typing after the link is bound into the link!  YUCK.

**Comment by JoelParke** [comment]
I have put a PR out that fixes this: #1279.  Please reopen if still an issue.
