### ISSUE TITLE
Shift + ENTER does not work only on Safari

### ISSUE THREAD

**Issue by isaquebressy** [fraywing/textAngular#1320]
On Safari, Shift + ENTER produces a new paragraph (P) tag.
I tested it with other browsers and all of them generated the right BR tag.

**Comment by JoelParke** [comment]
<p>I'm not sure what to do with this.  I testing on versions on the way back to 1.2.1 and it always does new paragraph tag.<br/>On v1.2.0 it has all sorts of issues, and a plain Enter just does a new line -- because it is generating &lt;div&gt;&lt;/div&gt; always.  But in this instance a &lt;Shift-Enter&gt; does generate a blank-line and then a new line.  </p><p>I can only test this under windows on a very old version of Safari.  What version of Safari are you using?<br/>Also - it looks HARD to fix without  breaking other browsers.  <br/>Do you have to use the Safari browser?  </p>

**Comment by JoelParke** [comment]
I am going to mark this as won't fix unless it is a big issue with the current modern Safari -- is that where you are seeing this issue, since I have only tested on the OLD safari on windows which is no longer supported by Apple.

**Comment by isaquebressy** [comment]
I'm using the version 9.1.3 (11601.7.8) of Safari for MacOS X. My OS is El Capitan v10.11.6 (15G1004).
You are correct. The Windows version of Safari is out of dated and is no longer supported by Apple.
Safari is my main browser and I am using textAngular to build an application for different browsers.

Thank you for your answer. If you have a way to test it on Safari for Mac I will appreciate it!
Thanks again!

**Comment by JoelParke** [comment]
Thanks much for the info.  I will look at in 2-3 weeks.  Have you tested an earlier version of TA?  If there was one that worked, it might help me see what changed!

**Comment by isaquebressy** [comment]
I tested the version 1.5.1 of TA.  
I tested also the editor demo on http://textangular.com

**Comment by JoelParke** [comment]
<p>I have checked in a PR #1360 which corrects this.  However this seems to go against the way Apple has set things up.  There is the same issue with complaints for Facebook.<br/>But I don't believe this change causes problems.<br/>Could you please check this fix, since I can only test on the older version of Safari on Windows. <br/>If there are still issues, please re-open.  </p>
