### ISSUE TITLE
"Handle overlay" isn't refreshed after windows resize

### ISSUE THREAD

**Issue by fts-mage** [fraywing/textAngular#1326]
Click on an image display an overlay that don't refreshed after window resizing.

**Comment by JoelParke** [comment]
I assume that what you see is something like:

![screenshot from 2016-09-20 09-52-06](https://cloud.githubusercontent.com/assets/12278498/18678055/0b032304-7f18-11e6-91a1-57f2efe711fb.png)

Which is a bit of an issue, but when would you want to resize the window when you were resizing the image inside?  Since there a bunch of other bugs on the plate to fix first.

**Comment by fts-mage** [comment]
For example (in Windows) by pane-right the editor window and pane-left an informative doc. Or by using tablet or other modern device able to change orientation. The editor will be used in email builder that allow user to build email on pc/tablet and phone (?). that's why i have to check how editor will react in those cases.

But, indeed, user can reclick the picture to see perfect overlay :)

**Comment by JoelParke** [comment]
This is corrected with PR #1350.  Please test. Thanks!
