### ISSUE TITLE
IE: cursor jumps to top position after pasting in IE.

### ISSUE THREAD

**Issue by tlumko** [fraywing/textAngular#1369]
I'm trying to paste some text in textAngular using IE11. After text is pasted, cursor jump to top left position. It is reproducible on textAngular demo page: http://textangular.com/.

**Comment by BLukash** [comment]
Same issue appears in my code.

**Comment by matthewbal** [comment]
Same issue here. Anyone found a workaround yet?

**Comment by matthewbal** [comment]
Horrible workaround:

To fix the jump on any toolbar button click, add code directly after
```
}]).factory('taToolExecuteAction', ['$q', '$log', function($q, $log){


	// this must be called on a toolScope or instance
	return function(editor){

```

Code:
```
var cPos = $(document).scrollTop();
setTimeout(function(){ 
	if (cPos != $(document).scrollTop()){
		$(document).scrollTop(cPos);
	}
}, 1);
```

To fix the jump on pasting text, add code directly after

`element.on('paste', scope.events.paste = function(e, eventData){`

Code (this section just needs a longer wait):
```
var cPos = $(document).scrollTop();
setTimeout(function(){ 
	if (cPos != $(document).scrollTop()){
		$(document).scrollTop(cPos);
	}
}, 50);
```

mess with the wait times if this doesnt work for you. Really terrible work around but it's better than the user having to scroll down themselves.

**Comment by JoelParke** [comment]
<p>I don't see this issue when using Edge. Should I close this issue, or is it still an issue.  For IE 11, TextAngular doesn't seem to work at all... <br/>Unless I need to change the default settings??? and is that worth the time, since MS edge seems to work fine???<br/>Obviously I don't use IE or Edge -- just Chrome.  But I would like to fix this if possible.  Does IE 11 work normally on Windows 10? </p>

**Comment by tlumko** [comment]
I can't reproduce it nor on Win7 neither on Win10 anymore. Bug exists in ver 1.4.6 but everithing is OK in 1.5.16.
