### ISSUE TITLE
What rangy files do I need to include?

### ISSUE THREAD

**Issue by robianmcd** [fraywing/textAngular#144]
Thanks for creating textAngular. It looks great! I'm just getting set up with it and I was wondering what rangy files I need to include? Just rangy-core.js? Also what differences will I notice?

Thanks!
Rob

**Comment by bbottema** [comment]
I was looking for this information. Maybe add this as a footnote somewhere in the docs?

**Comment by SimeonC** [comment]
@bbottema It's already in the readme - point 2 of the requirements. Current version of textAngular requires the rangy files though.

**Comment by bbottema** [comment]
@SimeonC I meant the reason why it is needed, especially since I had to add it manually as grunt wiredep didn't inject it automatically.

**Comment by SimeonC** [comment]
It's needed because the support for `execCommand` is really inconsistently implemented cross browser so we have to fill in the gaps with it.

I don't know how wiredep works so I can't comment on that - you can just use the `dist/textAngular-rangy.min.js` file which is just a compression of the needed files.

**Comment by bbottema** [comment]
Actually, textAngular is the only library currently giving me issues while auto injecting its dependencies. 

In addition to the rangy libs, the css file is also ignored. The other libs (textangular, sanitize and setup) are found and inserted. Is there something missing in your bower configuration?

```html
<!-- bower:css -->
<link rel="stylesheet" href="bower/font-awesome/css/font-awesome.css" />
.. bower/textAngular/src/textAngular.css missing ...
<!-- endbower -->

<!-- bower:js -->
<script src="bower/textAngular/src/textAngular.js"></script>
<script src="bower/textAngular/src/textAngular-sanitize.js"></script>
<script src="bower/textAngular/src/textAngularSetup.js"></script>
... bower/textAngular/dist/textAngular-rangy.min.js missing ...
<!-- endbower -->
```

**Comment by bbottema** [comment]
Actually, the bower config seems fine to me. I'm suspecting the rangy library didn't define a _main_ property in their bower config. I'll look further...

**Comment by bbottema** [comment]
Actually, because textAngular ships its own range.min.js, the dependency should be on that file as a _main_, instead of the rangy project as a _dependency_ property. That way it's clear what the concrete dependency is (the included version), instead of what it should be (the referenced range project, which is missing this information).
