### ISSUE TITLE
Lots of space on line break because of break wrapped in paragraph tags (e.g. <p><br/></p>)

### ISSUE THREAD

**Issue by johnwheeler** [fraywing/textAngular#272]
Hello -

This is a great directive and thank you for it. I have pasted a screen cap of the issue I have

I have textAngular above and a div bound to the same ng-model below. You can see that if I hit enter, there is a 

```
<p><br/><p>
```

inserted between line 1 and line 2 which makes for an extra large space. I am assuming this is by design - but I wanted to ask if there was a way to override this behavior as my users use the editor to compose simple HTML e-mail and the line breaks look better smaller (i.e. two `<br>`) to me? 

![screencap](https://cloud.githubusercontent.com/assets/6809734/3959473/5799bd44-272d-11e4-81df-a6e012472c9f.png)

**Comment by wdeangelis-op** [comment]
Hmm... I don't know if I agree with this solution. I have no control over the model data and often times many people use break tags instead of paragraph tags. When this happens I'm getting the exact same thing... `<p><br /></p>`. Would be way better to never wrap break tags in paragraph tags. Thoughts?
