### ISSUE TITLE
How to add tooltips to the toolbar or change the default name/icon?

### ISSUE THREAD

**Issue by uncedric** [fraywing/textAngular#375]
I'd like to be able to add tooltips to each button on the toolbar, since some of my users are not familiar with html and h1,h2,h3,etc is not clear enought for them :/

Any idea?

**Comment by muratsplat** [comment]
@SimeonC  How to override taTranslations value?  I can not do this by provider decorator..
I have read wiki page that https://github.com/fraywing/textAngular/wiki/Customising-The-Toolbar. I have no idea to override taTraslations..

**Comment by plumpNation** [comment]
@muratsplat I had similiar issues when I was using gettext, I needed to modify the translations after the decorator would have run.

I simply modified the taTools object directly, in the callback of a containing directive.

i.e. I created a directive which wrapped the textangular directive.

Above the returned directive configuration object for the wrapper directive, I make my modifications.

Some of the translations are used in the action function of the tool (like insertLink), and these you should modify on the taTranslations object, since that is what is being used in those functions.

For the tools (like Bold) where the tool is already set up, modify directly on the taTools object.

It isn't that pretty and is unlikely the correct solution, however I could not get the initial render of the directive to use my overrides unless I did this and I needed a feature out, with locale supported.
