### ISSUE TITLE
An Editor with name "..." already exists using ui-router

### ISSUE THREAD

**Issue by johannesjo** [fraywing/textAngular#410]
From time to time i get an error 

```
textAngular Error: An Editor with name "description" already exists <text-angular ng-model="issue.description" id="description" name="description" placeholder="Geben Sie hier relevante Informationen zu Ihrem Fall an." ta-max-text="{{ v.maxDescriptionLength - 0 }}" class="ng-isolate-scope ng-pristine ng-valid ta-root"> 
```

The element does only exist once in the whole application and is not inside a repeat of some sort.

**Comment by ShakurOo** [comment]
I have the same issue. 

In my view I have two textAngular areas, but this view is refreshing with dynamic url (http://example.com/city/:cityLabel). And this seems to be causing problem with directive. I have the error : 

> An Editor with name "..." already exists using ui-router

and if i try using one of my both textAngular areas I have this error :

> Cannot read property 'toolbarScopes' of undefined

There is a way to solve this ? :(

**Comment by eddapeturs** [comment]
So I ran into the same problem, where I was using the same directive (which used textAngular) in two views, and routing between the views using $state.go.

The solution that worked for me was just skipping a toolbar and not giving the text editor a name attribute. I was getting errors because the name for the editor needs to be unique, as well as the editor toolbar, and the taTargetToolbars attribute on the text-angular directive needed to math that name.

If you read the source code, you can see that textAngular checks if your editor has a serial attribute, and if not assigns one.
   `_serial = (attrs.serial) ? attrs.serial : Math.floor(Math.random() * 10000000000000000)`

Then it checks if the editor has a name, else assigns one using _serial:
    `scope._name = (attrs.name) ? attrs.name : 'textAngularEditor' + _serial;`

Then, it checks if the editor has a taTargetToolbars associated with it, and if so registers that toolbar, else it creates one for it, using the same serial number. So everything matches and is unique if you do it this way. I don't know if this is the ideal solution but at least now it works.

**Comment by billyryanwill** [comment]
@eddapeturs Nice one. This helped me out big time.

**Comment by neilmalgaonkar** [comment]
@eddapeturs Thanks a lot. This comment saved a lot of my time :)
