### ISSUE TITLE
Video Inserts Broken?

### ISSUE THREAD

**Issue by dg1202** [fraywing/textAngular#488]
Hi, 

Not sure if this is a bug, or Im just completely missing something. Is there some secret to adding video via the toolbar tool? 

I select the tool, get the pop up to add the url. I add `https://www.youtube.com/watch?v=SGUPXnsztxg` for a youtube link. (I've also tried http as well as the embed url -- none appear to work)  
  
All that is rendered is a box with a grey border. 

![screen shot 2015-01-13 at 7 07 59 am](https://cloud.githubusercontent.com/assets/2365581/5721103/0263d7da-9af3-11e4-8ca3-f5f2dc0e9e2c.png)

**Comment by SimeonC** [comment]
See the [FAQ](https://github.com/fraywing/textAngular#faq) in the readme.

**Comment by dg1202** [comment]
Well now I feel stupid. Thanks for pointing that out!

**Comment by dg1202** [comment]
` To display the youtube videos when you aren't in the editor use the following html: <div ta-bind ng-model="data.htmlcontent"></div>`  
  
So two questions.  
1. Why do videos not display while "in" the editor. Maybe my youtube url is incorrect? (again, I've tried embed links and the standard url to the video)  
2.  After applying the `ta-bind` to my main content html outside of the editor, I get the same results.  
  
Maybe I am still misunderstanding something here, but no luck so far.

**Comment by SimeonC** [comment]
Hey.

It's probably you haven't included textAngular-sanitize instead of angular sanitize. There have been a couple of issues detailing this but you'll have to find them yourself as I'm moving so I won't have time to find them properly till next week.

Thanks,
~Simeon

Sent from my iPhone

On 15/01/2015, at 2:28 am, Dave Gavigan <notifications@github.com<mailto:notifications@github.com>> wrote:


To display the youtube videos when you aren't in the editor use the following html: <div ta-bind ng-model="data.htmlcontent"></div>

So two questions.

1. Why do videos not display while "in" the editor. Maybe my youtube url is incorrect? (again, I've tried embed links and the standard url to the video)

2. After applying the ta-bind to my main content html outside of the editor, I get the same results.

Maybe I am still misunderstanding something here, but no luck so far.

-

**Comment by dg1202** [comment]
@SimeonC no worries. Thanks for the help. Ill shall go do some digging then.

**Comment by SimeonC** [comment]
Yea, I have had a few discussions about that particular quirk of textAngular. Glad you got it sorted in the end.
