### ISSUE TITLE
Use semver versioning for better bower compatibility

### ISSUE THREAD

**Issue by opengeekv2** [fraywing/textAngular#490]
Nowadays when you tell bower to get the latest version of textAngular it gets 1.3.0-pre9 insetad of  1.3.0-22. This is happening because you're not following the semver notation that bower uses to compare the releases. You should follow this notation for versions so bower can order your releases correctly.

You'll see this ordering running 'bower info textAngular' in your terminal.
You can find more information about the Semantic Versioning (semver) notation at:
https://github.com/npm/node-semver
http://semver.org/

**Comment by SimeonC** [comment]
That's due to a change in how I do pre-releases - both are actually semver it's just that I changed to using grunt-bump for automation half way through. Rest assured in future all of the versioning is done by grunt-bump so this won't be an issue in future pre-release cycles (Hopefully I'm very close to a 1.3.0 full release which should fix this too).

(The following is point 9 from semver.org)
> A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-]. Identifiers MUST NOT be empty. Numeric identifiers MUST NOT include leading zeroes. Pre-release versions have a lower precedence than the associated normal version. A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version. Examples: 1.0.0-alpha, 1.0.0-alpha.1, 1.0.0-0.3.7, 1.0.0-x.7.z.92.
