### ISSUE TITLE
In Google Chrome, when toggling a list item (ie: on-off-on or bullet-number-bullet) the original style is lost

### ISSUE THREAD

**Issue by darcyparker** [fraywing/textAngular#5]
This problem does not occur in FF 24.0

I tested this on Google Chrome `Version 30.0.1599.69 m` and also on `Version 32.0.1667.0 canary Aura`.

When I toggle a list item such as one in the demo: http://textangular.com/, I see a `span` element wrapped around the text node like:

``` html
<span style="font-size: 1.2em; line-height: 1.428571429;"> .... </span>
```

Perhaps it is a bug with `execCommand` on Chrome that textAngular needs to work around?

Markup at beginning:

``` html
<h2>Try me!</h2><p>textAngular is a super cool WYSIWYG Text Editor directive for AngularJS</p><p><b>Features:</b></p><ol><li>Automatic Seamless Two-Way-Binding</li><li>Super Easy <b>Theming</b> Options</li><li>Simple Editor Instance Creation</li><li>Safely Parses Html for Custom Toolbar Icons</li><li>Doesn't Use an iFrame</li><li>Works with Firefox, Chrome, and IE10+</li></ol><p><b>Code at GitHub:</b> <a href="https://github.com/fraywing/textAngular">Here</a> </p>
```

After putting cursor in the line with item 1 and clicking **ordered list**.

``` html
<h2>Try me!</h2><p>textAngular is a super cool WYSIWYG Text Editor directive for AngularJS</p><p><b>Features:</b></p><span style="font-size: 1.2em; line-height: 1.428571429;">Automatic Seamless Two-Way-Binding</span><br><ol><li>Super Easy <b>Theming</b> Options</li><li>Simple Editor Instance Creation</li><li>Safely Parses Html for Custom Toolbar Icons</li><li>Doesn't Use an iFrame</li><li>Works with Firefox, Chrome, and IE10+</li></ol><p><b>Code at GitHub:</b> <a href="https://github.com/fraywing/textAngular">Here</a> </p>
```

Continuing to toggle **ordered list** does not wrap the text() node with an additional `span` element.

As mentioned in description, similar behaviour occurs when toggling between **unordered list** and **ordered list** too.

**Comment by simonfox** [comment]
I know this is old, but I got here via the related chromium issue (using the [pell editor](https://github.com/jaredreich/pell)).

I've tracked this down to the existence of a style that contains a `font-size` definition that uses `em`, `rem`  or `pt` units that cascades to the `contenteditable` element i.e. I had the following in my styles
```
body {
  font-size: 0.9em;
}
```
 which resulted in a additional span wrapper with attribute `style="font-size: 0.9em;"`. Either removing `font-size` from the `body` style or setting the `font-size` directly on the `contenteditable` using `px` units returns the expected behavior.

Hope this helps anyone who stumbles across this!
