### ISSUE TITLE
Add padding when focus

### ISSUE THREAD

**Issue by wise007** [fraywing/textAngular#553]
Hello guys,

at first, really great work, i like it! :+1: 

What is my problem and what i need.

I need toolbar always at bottom of page, at fixed position. 
To do that i change element for toolbar prepend to `$('body').prepend(_toolbar);`.

It works great.

By i need to add padding to root element when focussed, otherwise toolbar is over text.

To do that i thought it should be enough add my line (for example `$('#wrapper').addClass('padding')`) to `focus` function at line 2317, but it's not working.

Everything is shown at video here: fbman.cz/error.mov

I dont want to use another plugin, i spent hours trying to resolve this problem, but i'm probably at the end.

Can u help me? Thanks lot!

Jakub

**Comment by SimeonC** [comment]
OK, first off, upgrade to 1.3.7 - there's a serious XSS bug that was fixed in the new version.

I think you're actually going about this the wrong way, you shouldn't need to edit the textAngular.js code for either of those functions. Have a look here: http://plnkr.co/edit/NYVbxtmz9Pw1paVLboE8?p=preview

I've used the ta-target-toolbars attribute that allows me to split out the toolbar to a different place, then to add the padding I've just added a CSS rule.

**Comment by wise007** [comment]
I can't do this like you have. I have more editors at one page and i need to change css of another div. But i used rootScope and it's working. I'll upgrade, thank you.

**Comment by SimeonC** [comment]
Hmmm, I'm pretty sure you can, here's an example where I'm using two editors and one toolbar at the top. Each editor has different CSS applied via ID selectors. http://plnkr.co/edit/NYVbxtmz9Pw1paVLboE8?p=preview

**Comment by wise007** [comment]
But i dont want to change css of editor, but body for example.

**Comment by SimeonC** [comment]
Ahh, I see. In that case you can make use of the `ng-focus` directive to add your class to the body - we support the default angular functionality of that. `<text-angular ng-focus="functionHere()"></text-angular>`
