### ISSUE TITLE
Change name of default tools

### ISSUE THREAD

**Issue by figalex** [fraywing/textAngular#577]
I have read the documentation about adding new tools, but all I want to do is just change the text on some of the default tools buttons. Is there a way to do this without adding a new tool?

**Comment by SimeonC** [comment]
Yes, you can change it by modifying the [textAngularSetup.js](https://github.com/fraywing/textAngular/blob/master/src/textAngularSetup.js) file and editing them there. That's the reason we have it in a different file so that you can just use your own version as needed. Just don't use the pre-minified versions bundled in - just grab the un-minified ones and do the minification yourself if needed.

**Comment by figalex** [comment]
That's great, thanks!
