### ISSUE TITLE
Issues when runs window.rangy.init(); (Line 1832 at textAngular.js)

### ISSUE THREAD

**Issue by gabrielhahn** [fraywing/textAngular#638]
We're facing some issues when the application starts and we try to edit a text. Then, we've made a workaround using $timeout to start window.rangy.init(); after 50 milisecconds.
Without that workaround, the application doesn't recognize the getSelection method from rangy module.
The console error says "TypeError: rangy.getSelection is not a function"

**Comment by jaisonerick** [comment]
I'm having the same issue. I did a little dig on this. This issue seems to happen inside the Rangy library.
Inside https://github.com/timdown/rangy/blob/1.2.3/uncompressed/rangy-core.js file, starting at line 2512, there's a test to check if the browser supports multiple ranges. On line 2532, it tries to call addRange on 'sel', that is null. The fix above works for me, but I don't really know why.

By the time that rangy tries to call getSelection (line 2524), looks like the document still not loaded, and when we but a 50 ms timeout, it gives time enough for rangy to works. 

I was looking into the master version of rangy, and seems like the issue is fixed. The file now is https://github.com/timdown/rangy/blob/master/src/core/wrappedselection.js and the above checking starts at 131. There's also a comment explaining some errors in IE (with me, the error occurred with firefox last version).

I believe that updating the rangy version would solve this issue.
