### ISSUE TITLE
bootstrap-css-only dependency

### ISSUE THREAD

**Issue by ArdentKid** [fraywing/textAngular#649]
This dependency breaks some of the custom bootsrtap varialbes I've set, and some default ones in bootstrap-sass-official (dependency somewhere else). I'm trying to figure out what's the best way to deal with this sort of thing, since it could happen in other places with other sub-dependencies in bower. How do people normally deal with it? If I simply remove the dependency, I have to remember to do it whenever I re-install my bower components.

**Comment by SimeonC** [comment]
I don't remember that coming up before but there's a request out for removing it so if you want to move all the css code we use into our css file from bootstrap and submit it as a PR removing the dependency that would fix it.

**Comment by frankthelen** [comment]
I have exactly the same problem...

The "bootstrap-css-only" dependency from textAngular is overwriting some of the Bootstrap customizations in my project (based on "bootstrap-sass-official"). And I don't have any chance to opt-out the "bootstrap-css-only" dependency coming from textAngular -- Bower is pulling it into my project automatically.

I vote for removing this dependency from textAngular, This lets people chose the Bootstrap package they actually need, e.g., "bootstrap", "bootstrap-sass-official", "bootstrap-css-only", or whatever.

I have seen this in a couple of other projects/packages.

Thanks a lot, 
Frank

**Comment by pbassut** [comment]
+1

**Comment by pbassut** [comment]
@frankthelen Just removing the dependency from bower will only break the plugin considering that it stills needs the dependency.

**Comment by frankthelen** [comment]
Yes, right, you have to add the Bootstrap package of your choice to your __direct__ project dependencies.

**Comment by pbassut** [comment]
I thought the idea was to remove the dependency and create a brand new css style to textAngular. Thus, not conflicting with any other bootstrap or custom style. Adding prefix like '.ta-bootstrap' to css classes would be a good way to go.

Because some people like myself don't want to use bootstrap at all.

But still, removing the dependency will make people that just heard of the library to get confused about make it work out of the box.

Guess I was wrong though.

**Comment by frankthelen** [comment]
If you don't want to use Bootstrap at all, adding "bootstrap-css-only" to your direct project dependencies should work. 

Making textAngular not depending on Bootstrap at all is a valid approach too. Sure. 

But __if__ you use Bootstrap, you want, e.g., that the textAngular Buttons inherit the properties of your customized Bootstrap, for example, the button border radius. Otherwise textAngular will conflict with your Bootstrap theme.
