### ISSUE TITLE
How can I add a input box(can be a div or <input type=text>) inside textangular editor

### ISSUE THREAD

**Issue by nikhilvm1993** [fraywing/textAngular#722]
How can I add a input box(can be a div or <input type=text>) inside textangular editor,that accepts input and append its contents with Textangular.and content along with input box should hide and show on a button click in tool bar??

**Comment by nikhilvm1993** [comment]
When i tried with an input box,it accepts data,but they are outside the scope of editor,

**Comment by JoelParke** [comment]
Not sure what exactly you need.  One thing I discovered recently was how easy it was to get to almost any scope in the DOM.  In my case, I had a controller that was handling file downloads and I need on success to add a link back to textAngular.  What I did was to add a button in the toolbar.  This button initiated the file download.  I also added a function in the tool bar code that the file download controller would call on success.  

In terms of the finding the scopes I needed, I used the following code in the controller:

    var appElement = document.querySelector('[ng-app=tracker2App]');
    var $appscope = angular.element(appElement).scope().$$childHead;

This gave me the scope to access my main application controller.

I had a progress bar in my toolbar items I added to textAngular with this code:

     taRegisterTool('progress', {
        display: "<div class='progressbar' ng-show='showProgress'><progressbar value='progress_value'></progressbar></div>",
        action: function (deferred) {
          var self = this;
          return true;
        }
      });

So since this one toolbar item has a div.progressbar in the html, I was able find the other scopes I needed with:

        var progressElement = document.querySelector('div.progressbar');
        var $progress_scope = angular.element(progressElement).scope().$parent.tools['progress'];
        var $addfile_scope = angular.element(progressElement).scope().$parent.tools['addFile'];
        var $addimage_scope = angular.element(progressElement).scope().$parent.tools['addImage'];
WHERE the 'progress', 'addFile', and 'addImage' were the three toolbar items that I had added.

NOTE that I needed to put console.log() messages that I looked at in the browser in order to discover  out how to access the scopes I needed.

I hope this help you in finding code to get to the scope that you need to pass the data from the input to where it is needed.

**Comment by nikhilvm1993** [comment]
Thank you very much
