### ISSUE TITLE
Event object in taRegisterTool action

### ISSUE THREAD

**Issue by DaveRevay2** [fraywing/textAngular#743]
Is it possible to get the event object in the taRegisterTool action function?

I would love to have something like this:
```
        taRegisterTool('insertLinkCustom', {
            iconclass: 'fa fa-link',
            action: function(promise, restoreSelection, event){
              console.log('Yay, JS Event object ' + event)
            },
        });
```

This would be very useful. Angular material modals require this for their animations. The window.event object is not available in firefox so it must be passed in from the click bind.

**Comment by Londovir** [comment]
I just made this modification for my own application because using Angular Material's md-button objects in place of the usual ones in the toolbar was causing odd event bubbling issues. Here's what I did to enable it (my line numbers may be a bit different in my version due to some other customizations I have done):

Around Line 395 (textAngular.js), change the following:
```javascript
}]).factory('taToolExecuteAction', ['$q', '$log', function($q, $log){
     // this must be called on a toolScope or instance
     return function(editor){
```

to this:
```javascript
}]).factory('taToolExecuteAction', ['$q', '$log', function($q, $log){
     // this must be called on a toolScope or instance
     return function(editor, $event){
```
(Added `$event`)

Around Line 2672 (textAngular.js), change this:
```javascript
     toolElement.attr('ng-click', 'executeAction()');
     toolElement.attr('ng-class', 'displayActiveToolClass(active)');
```

to this:
```javascript
     toolElement.attr('ng-click', 'executeAction(undefined, $event)');
     toolElement.attr('ng-class', 'displayActiveToolClass(active)');
```
(Added `$event`)

Then, in any `action` method you define, you'll want to be sure to include the `event` parameter as you noted in your OP.

**Comment by DaveRevay2** [comment]
Thanks @Londovir 
@SimeonC, is this sort of thing suitable for master?

I think there are more and more people moving from bootstrap to angular material so it'd be nice to support this. I've just removed bootstrap dependency from my [project](https://stemn.com/blogs/the-story-of-stemn-(so-far)?edit=BlogForm) and have been very happy since.

**Comment by pbassut** [comment]
There's an open issue regarding the removal of bootstrap. #625
