### ISSUE TITLE
Alt-Z shouldn't be undo with Windows+Polish keyboard

### ISSUE THREAD

**Issue by ByteMug** [fraywing/textAngular#799]
If you have Windows with the "Polish (Programmer)" keyboard layout, you can input polish character "ż" (z with a dot over it) using Alt+Z. 
TextAngular always maps alt+z as "undo", which makes using it in Poland kind of impossible.

**Comment by Pitros** [comment]
For me works fine both undo and typing ż, as well any other polish letter (lastest angular, textAngular and running nw.js).

**Comment by pbassut** [comment]
@ByteMug I don't know a way to test this since my keyboard is english. But @Pitros says it's working fine. Which makes me think it's an environment issue. Could you provide more information like the browser, OS, etc.

**Comment by ByteMug** [comment]
On my PC it's Windows 7 with the newest Chrome and Firefox. Both maps alt-z as undo. 
Client's testers have W8 with some older (but still new) Firefox. Gonna give you more details on Monday.

**Comment by JoelParke** [comment]
I'm thinking that we should be able to set the key that is associated with undo..... When we know more, we may understand what we can do!

**Comment by ByteMug** [comment]
@pbassut Alt-z isn't even captured by event.keyCode. It doesn't return anything when for example Alt-c returns keyCode 263 which gives "ć". I don't know how can I give you more info. Alt-Z is undo on every browser and computer in my office.

**Comment by JoelParke** [comment]
<p>Have looked at the enhancement to taOptions:<br/></p><pre style="background-color: #ffffff;color: #000000;"><span style="color: #808080;"><i>///////////////////////////////////////////////////////////////////////////////////////<br/></i></span><span style="color: #808080;"><i>// keyMappings<br/></i></span><span style="color: #808080;"><i>// allow customizable keyMappings for specialized key boards or languages<br/></i></span><span style="color: #808080;"><i>//<br/></i></span><span style="color: #808080;"><i>// keyMappings provides key mappings that are attached to a given commandKeyCode.<br/></i></span><span style="color: #808080;"><i>// To modify a specific keyboard binding, simply provide function which returns true<br/></i></span><span style="color: #808080;"><i>// for the event you wish to map to.<br/></i></span><span style="color: #808080;"><i>// Or to disable a specific keyboard binding, provide a function which returns false.<br/></i></span><span style="color: #808080;"><i>// Note: 'RedoKey' and 'UndoKey' are internally bound to the redo and undo functionality.<br/></i></span><span style="color: #808080;"><i>// At present, the following commandKeyCodes are in use:<br/></i></span><span style="color: #808080;"><i>// 98, 'TabKey', 'ShiftTabKey', 105, 117, 'UndoKey', 'RedoKey'<br/></i></span><span style="color: #808080;"><i>//<br/></i></span><span style="color: #808080;"><i>// To map to an new commandKeyCode, add a new key mapping such as:<br/></i></span><span style="color: #808080;"><i>// {commandKeyCode: 'CustomKey', testForKey: function (event) {<br/></i></span><span style="color: #808080;"><i>//  if (event.keyCode=57 &amp;&amp; event.ctrlKey &amp;&amp; !event.shiftKey &amp;&amp; !event.altKey) return true;<br/></i></span><span style="color: #808080;"><i>// } }<br/></i></span><span style="color: #808080;"><i>// to the keyMappings. This example maps ctrl+9 to 'CustomKey'<br/></i></span><span style="color: #808080;"><i>// Then where taRegisterTool(...) is called, add a commandKeyCode: 'CustomKey' and your<br/></i></span><span style="color: #808080;"><i>// tool will be bound to ctrl+9.<br/></i></span><span style="color: #808080;"><i>//<br/></i></span><span style="color: #808080;"><i>// To disble one of the already bound commandKeyCodes such as 'RedoKey' or 'UndoKey' add:<br/></i></span><span style="color: #808080;"><i>// {commandKeyCode: 'RedoKey', testForKey: function (event) { return false; } },<br/></i></span><span style="color: #808080;"><i>// {commandKeyCode: 'UndoKey', testForKey: function (event) { return false; } },<br/></i></span><span style="color: #808080;"><i>// to disable them.<br/></i></span><span style="color: #808080;"><i>//<br/></i></span><span style="color: #660e7a;"><b>keyMappings </b></span>: [],<br/></pre><p><br/>So that if you set taOptions<br/></p><pre style="background-color: rgb(255, 255, 255);"><span style="color: rgb(102, 14, 122);"><b>keyMappings </b></span><font color="#000000">: [&#10;</font><font color="#000000">   </font><i style="color: rgb(128, 128, 128);">{ commandKeyCode: 'UndoKey', testForKey: function (event) {&#10;</i><i style="color: rgb(128, 128, 128);">       </i><i style="color: rgb(128, 128, 128);">if (event.keyCode=57 &amp;&amp; event.ctrlKey &amp;&amp; !event.shiftKey &amp;&amp; !event.altKey) {&#10;</i><i style="color: rgb(128, 128, 128);">          return true;&#10;</i><i style="color: rgb(128, 128, 128);">       } &#10;   },&#10;   { ... } ],</i></pre><p>Then the UndoKey should be set to Ctrl+9.  Or you can set this to what ever you wish.<br/>Please let me know if this issue can be closed...</p><p></p>

**Comment by ByteMug** [comment]
Thanks
