### ISSUE TITLE
Question: dynamically update elements within the textarea?

### ISSUE THREAD

**Issue by JamesChangVerifi** [fraywing/textAngular#807]
Hi there,

So I'm doing some preliminary research for a project, and was wondering if you could tell me whether the following is possible in textAngular: we're interested in binding the values of some fixed input boxes to specific elements *within* the textarea, ideally with an ngBind.

For example, let's say the text editor contains the following HTML, which we'd have Angular compile after being loaded:

    <div>
    This is editable text, and this <span ng-bind="name">variable</span> should be bound to the name property on a model.
    </div>

Outside the text editor, we'd have an input box also bound to *name*; changes in this input box would update the ng-bound span within the text area, and editing the span itself ideally should also change the value in the input box.

However, after digging through previous questions it seems to me that compilation in the editor isn't supported, as mentioned in https://github.com/fraywing/textAngular/issues/52 and https://github.com/fraywing/textAngular/issues/323. Is the use case we're interested in possible?

Thanks!

**Comment by pbassut** [comment]
As you pointed out: this is not supported due #52, and also #62 as I see it.
So, you could join the discussion at #52 to help us provide a better solution to this. Because as stated in that discussion, it brings a lot of problems and solves just one.

I'm closing this since there's a discussion open for that. Thanks for pointing out though
