### ISSUE TITLE
Adding attributes to a link

### ISSUE THREAD

**Issue by Awelemdy** [fraywing/textAngular#814]
I have been working all morning trying to add an attribute like ng-click to an a link. I can see that when I inspect the html that the attribute is there however, the attribute isn't visible when I try to access it from the ng-model javascript variable which is bounded to the editor. Is this a known issue?

It seems like something internally is stripping the attribute. What solutions would you guys recommend I utilize?

**Comment by JoelParke** [comment]
Awelemdy, I haven't looked ta this issue, but since you are in the middle of it.  The textAngular-sanitize is the software that was forked from angular-sanitize, so that is where I would look.  If there is a bug in this, it would be good to know and fix.  Or if this is expected behavior, you could cusomize your own sanitize code and do something there.  I hope this helps.  Let me know how it goes.
Joel

**Comment by Awelemdy** [comment]
The only solution is for me right now is to detect ng-click and if it is there, skip the sanitization. I don't like this solution so please if anyone does think of something please let me know.

**Comment by nickknissen** [comment]
You can add `ng-click` to `htmlAttrs` in [`textAngular-sanitize.js`](https://github.com/fraywing/textAngular/blob/master/src/textAngular-sanitize.js#L224)

**Comment by Awelemdy** [comment]
Adding ng-click to the htmlAttrs worked, thanks.
