### ISSUE TITLE
Access toolbar and leave editor with keyboard

### ISSUE THREAD

**Issue by m-hauptma** [fraywing/textAngular#820]
Is it a known issue that the toolbar is not accessible with the keyboard and a user has no possibility to leave the editor while only using the keyboard to tab through the elements? 

With 1.4.2 one new feature ("Enhanced toolbar to handle TAB and SHIFT-TAB KEYS.") has been introduced. However, this feature only enables to use TAB and SHIFT-TAB to de/increase indent. 
It would be great to have the possibility to disable the feature and enable leaving the editor since the focus is currently trapped.

**Comment by pbassut** [comment]
[This PR](https://github.com/fraywing/textAngular/pull/805) does exactly this. 
It supports binding key combinations to buttons on your toolbar. It was originally developed to solve the issue where polish(I think) keyboards can't use alt+z to undo because in a polish keyboard layout it means a z with two dots in it.

So, wait for the next release or get that PR and you're good.
