### ISSUE TITLE
is there any support for copy-paste in textangular.

### ISSUE THREAD

**Issue by himanshubisht** [fraywing/textAngular#826]
Hi ,

i am trying to use ng-paste on textangular but  not able to get clipboard data.

Is there any way to do this ?

**Comment by pbassut** [comment]
What are you trying to achieve? What's happening when you try it? We need more information to help you solve your issue.

**Comment by nachoargentina** [comment]
I think that instead of ng-paste you should try ta-paste.

Event is ta-paste="expression", result of the expression in the attribute will be the pasted string. Stupid example: ta-paste="'[No Paste]'" Inserts [No Paste] every time you try to paste. Better example is this: ta-paste="pasteHandler($html)" $scope.pasteHandler = function(html){return html.replace(/<(\/|)b>/,'<$1i>');}; which I do believe will replace all b tags with i tags.
