### ISSUE TITLE
HTML without paragraph

### ISSUE THREAD

**Issue by Goldfinch** [fraywing/textAngular#879]
Can I prepare html code without tag 'p'?
I mean, if I write some sentence in editor and remove from code paragraph tag , then send data, I get sentence with 'p' tag, that I removed before.
I would like clean sentence in this example. If I removed p from code, I shouldn't get it.

**Comment by pbassut** [comment]
It's an html editor. The text must be wrapped on something. I mean, how would the editor know when there's a new line, for example?
Tell me what you want to achieve and I'll try to help you out.

**Comment by Goldfinch** [comment]
http://clip2net.com/s/3nt9cbP
I deleted paragraph in second string, but in form it's still

**Comment by pbassut** [comment]
There can't be a text that's not wrapped within a tag. For example, what the editor is gonna do if you go to view mode and select this text and try to style it as bold? Since it's a text that's floating around without any specific tag, the editor won't be able to bold that text only. That's why having a text without a tag isn't supported.

**Comment by Goldfinch** [comment]
I understood. Thanks for explain.

**Comment by pbassut** [comment]
Anytime. You're welcome.
