### ISSUE TITLE
Custom toolbar not deactivating

### ISSUE THREAD

**Issue by Jebedo** [fraywing/textAngular#919]
I can't reopen so just a link to old issue:
[#910](https://github.com/fraywing/textAngular/issues/910#issuecomment-144329557)

**Comment by pbassut** [comment]
Why are you using queryCommandState?

**Comment by Jebedo** [comment]
We'll I hoped that I will force false state, or maybe true. Wasn't really sure. Doesn't work with it or without it. 

Plunker:
http://plnkr.co/edit/P0Ur06cyr6CRoNP0tqXJ?p=preview

**Comment by pbassut** [comment]
queryCommandState is meant for the browser to know it a command is occurring on that particular position where the cursor is in. For example: bold, italic, etc. Since you command is a custom command I'm not sure it would work. Take a look [here](https://developer.mozilla.org/pt-BR/docs/Web/API/Document/queryCommandState).

You have several problems with your script:
* It's actionState, not actionstate;
* h7 tags are not valid (it's only from h1 to h6). Thus, it's wiped out by the sanitizer;
* Using a empty activeState command it will never check if the button is active, because well, it's empty;

Use this code with the modifications I specified just now:
```
taRegisterTool(
                            'insertEKS', {
                                iconclass: 'fa fa-eur',
                                tooltiptext: "Unesi EKS",
                                action: function() {
                                    var textAngular = this;

                                    textAngular.$editor().wrapSelection('insertHTML', '<h2>EKS</h2>', true);
                                },
                                activeState: function() {
                                  console.log(this.$editor().queryFormatBlockState('h2'));
                                  return this.$editor().queryFormatBlockState('h2');
                                }

                            });
```

**Comment by Jebedo** [comment]
Thank you very much. You cleared some things for me. 

So this works now, and can be closed. 

But I have one question that I see in live demo:

When I deselect H tag text, text is back wraped in P tag. This is intentional?
