### ISSUE TITLE
ReferenceError: Can't find variable: require

### ISSUE THREAD

**Issue by sylouuu** [fraywing/textAngular#990]
Hi,

I want to use Karma for testing and it tells me:

```
ReferenceError: Can't find variable: require
at /<path>/text-angular/textAngular-rangy.min.js:2
```

I'm using the latest version 1.4.6.

Bests

**Comment by ibedard16** [comment]
I ran into the same issue recently, and I don't think this is an issue with textAngular. Pretty sure the issue  is caused by `angular-mocks.js` overwriting the `require` variable needed by rangy. 

You should try fixing the issue by putting `angular-mocks.js` after `textAngular-rangy.min.js` in your karma config file, like this:
```
files: [
      '<path>/textAngular-rangy.min.js',
      '<path>/angular-mocks.js',
      ]
```
I hope this fixes the issue!

(Just to be safe, you may want to put `angular-mocks.js` after all external dependencies, since you probably won't be testing them and some dependencies might run into the same issue.)

**Comment by sylouuu** [comment]
Hey @ibedard16,

Sorry for the late answer. Your tip works like a charm!

Thank you

Bests
